name: Pull from VPS

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull from VPS
      run: ssh -p 5225 ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /home/alexis/proyectos/testpipeline && git pull'
      env:
        SSH_USER: ${{ secrets.USERNAME }}
        VPS_HOST: ${{ secrets.HOST }}
        KEY: ${{ secrets.SSHKEY }}