name: Pull from VPS

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Show SSH_USER and VPS_HOST
      run: |
        echo "SSH_USER: ${{ secrets.SSH_USER }}"
        echo "VPS_HOST: ${{ secrets.VPS_HOST }}"

    - name: Pull from VPS
      run: |
        ssh -p 5225 ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST }} 'cd /home/alexis/proyectos/testpipeline && git pull'
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}

    - name: Add SSH key to known_hosts
      run: |
        ssh-keyscan -p 5225 ${{ secrets.VPS_HOST }} >> $HOME/.ssh/known_hosts
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
      