name: Pull from VPS

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Pull from VPS
      run: ssh -p 5225 ${SSH_USER}@${VPS_HOST} 'cd /home/alexis/proyectos/pipelines/ && git pull'
      env:
        SSH_USER: ${{ secrets.SERVER_USERNAME }}
        VPS_HOST: ${{ secrets.SERVER_HOST }}
